travis:
  secure:
    BINSTAR_TOKEN: jQoEvrjdTt+LPLf/QTktniJtq/KbiCKbqZ2FjOsooJlN5bEU6p708QecuLPeY+1FtOBKSjEM+HAaS5Zh9ZjAwVzM6+8ahv59pL/cuestwQuc9zhjtas3fNhm+INMxnko9w3enz+sfulSSi9zQjRU3rP/etIj576sziyqcb3fd6Bx9L09l6weVzqY5GWbRs9yaanHTko4M5DtF0Qifz24eFAQLjGKaAQpsgKwerNIvCmu6fTQN82tvRWd2hYlU5HzOisH2ByKu5Zueu23gwfpjeohQYBdFsZt38MLxNXLahD0Njh8yiS1Lw/wGtZwvyTpR6evX5OpVJbjAhfU0bUjEzUxaE8We8oz0yvC8aRgLcGh18vV6To4CQBe6vSOEQZ1DfD0TvzOD91a639Tw+iybMG7G+235gAGj8fPddDkr7uw7eHjC0p7q0kTzdPqhSG7K2kyyUj7hK3xD+UYxWreIGyCtCwbtWG+BdM3xvvZmeCf5vhD8EnxbolyIbANCDbQ2RwGzUmpny4rJJDjPrnoWQIaC8rzAuHCWAjmep1WKIc+ToPKWTSLerus7fHS5Oxud6wSCpcn9Bc34f2FCiebfjpxVKfy4RWac1ArbmEEgwddjdxyM5SY5H9FihUldZpB0rznzbghI/FYfJNls/g+kNSy0QggneZTLixMdcYIrKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
