travis:
  secure:
    BINSTAR_TOKEN: P/UlqpSkOeeT74n5Ew9wlp3til7GdmxMv0HuocI0Se6u9YcNxOE/ciFe9ymsneUHk4tWkfaHDVdPe83oNlRG/Mopnbi/gmeP/BeWINgtD4gf2xez8tcE/wz96mTUX9TiK/RN8qkGWybWLXnH6IePheROGJLh7JcHs+4NtfT/fW9S6EvcJ95598ya+WzYtW56I9k73GMt3pcPQMLb72eg5rmNiFyN3t/okAv9VAwChdsAO9bBUsSpwrYGgt8MWEpOJiwILhQJSRxGFm6aou5WPg5mcnX2kQe4nyrCHC4LVgb2cXSVetAAMf2BUAczjy/ecuU6LfVKa3g35XqCLgtUmi3915fUspowMq7WipGX76Hc/dv0nQjMGTIKtK6vtcoJrh2vJl6gbwxx3iyfRLlpq8XDYc97fbP7yKswt5y/0RJ81XTFcygxaa4XcokCL9dC60hj9kKEk6nHiyQ+5bcamRTJoITxIBSHs1apWTGKWtC1DVxjO/uu0qqLNzLx9SOeTdKzmXUfacKuViQmceFUJReZhUp2IiooRZKyPUP10GMHYliteY4KFCaahruu05xtJhh7+vkH+tCSMclQuaHvg0f2i17JXuqZ7poR7fWbmIEFKgvDDJdpWYvcfsCCw3N5fXJtkv1UdXtXxkvLTAV5y6Eb7qWNUih3eOZ5yILb/08=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
