travis:
  secure:
    BINSTAR_TOKEN: egyFSbIrVsI7QrG674uSo+oGoCBBrR6wOvffvDxmbax99nvAkFNBekiQZAbZz06W28bhA775E086WNqS8/DNZ6hZ2Ob4gL4/sDXkxq3dadL+rD0m/GoRUvMH2uuyv/hMWR0CKj/VzTRqCdDjHGC7PXMXf+fa92t2zu4S7RfTI4OHFMjgf/9dfWDogirx9l8RID0s1XdbNtBbHxjwS/NxjcWa1SC/oJadzaISQXqQT+uD0B3UW2Ok0XZtxwINT+OdUVz7G/kcFYg/xrYBMvQeNYs8lwPUmEypFYtGsQFJamDySpj3Mu7ZeQUPhY59OMe6SH8Ri+EsZkqe+vwiLg0gUSxUvAJeZGmGaX2juV1GVAurVfQEb2Dcp4OaqnsceJrwB5RXECVcKQccBpni8pGHdRnbv/N2fZ3AUGi4cBJ3/t6dp5vB2kt+OSntteFB3ooai9wu8ptASrihRKjkUKEsDP9QZQ1EJEQnvyCiqHGLpKaqlrjUQdwiDjzdRKm6GizOF04yA1Ew97vt9h4CESSUO7Ysd34Si2QKYdp8Sf+FJeWQWMjYAmIxXylBVEEYJfRtMBm+yUIONmvCDMKmJYYRV9erjGCXe9H2KlxFHvT+7718lOAd1GJj3D3g64sySHWdmajFIq5qcEDl4ECA2M2X2p+4cBqzhs+uA8tuTtsUEjk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
